### PR TITLE
[SPH-TASK] [Wireframes] User-Profile

### PR DESCRIPTION
**Pull request by Banggum05**
## Task Link

- https://app.asana.com/0/1202720049437748/1202820156452143/f

## Commands

- npm start

## Pre-conditions

- The Frontend developer must be in the fe folder.
- Has (npm install semantic-ui-react) installed
- react router dom must be v6.3.0 (npm install react-router-dom@6.3.0)

## Expected Output

- Run a Use Profile page

## Notes

- non responsive to size

## Screenshots
-
image

### CODE REVIEW

**Comment by clementpatt** [comment]
I think you have to add the routes in index.js as well

Screen Shot 2022-08-18 at 7 10 13 PM
Screen Shot 2022-08-18 at 7 10 35 PM

**Comment by Banggum05** [comment]
image
Here is my code for the routes and I don't think that I include routes in index.js.

image
here is for the index.js

**Comment by clementpatt** [comment]
Mine is like this

App.js
Screen Shot 2022-08-18 at 8 08 13 PM

Index.js
Screen Shot 2022-08-18 at 8 08 20 PM
 
 I'm also currently in your git branch
Screen Shot 2022-08-18 at 8 08 04 PM

**Comment by Banggum05** [comment]
Just add <App /> in index.js. Instead of <React.StrictMode /> so you can  properly check my PR.

root.render(<App />)

**Comment by clementpatt** [comment]
Looks good to me 

Screen Shot 2022-08-19 at 12 11 00 AM

**Comment by Banggum05** [comment]
Btw all my task are here in this commit. UserProfile, Intern User Profile/ Other User Profile, and Edit profile page

**Comment by biancanailon** [comment]
Is this in your branch or this is wrong on my part lang?
image

**Comment by biancanailon** [comment]
please change the routing base on figma
`/profile ` => `/dashboard/profile`

**Pull request merged**
